server:
  port: 8000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-a
          uri: lb://service-a
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        service: gateway